# Generated by Django 2.0.13 on 2019-10-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),

    ]
