# Generated by Django 2.0.13 on 2019-10-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
