# Generated by Django 2.0.13 on 2019-10-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='image',
            field=models.ImageField(upload_to='products_pics'),
        ),
    ]
