# Generated by Django 2.0.13 on 2019-10-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191023_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='products_pics'),
        ),
    ]
