# Generated by Django 2.0.13 on 2019-10-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191023_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
