# Generated by Django 2.0.13 on 2019-10-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
