# Generated by Django 2.0.13 on 2019-10-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='price',
            name='service',
        ),
    ]
