# Generated by Django 2.0.13 on 2019-10-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191026_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='service',
            name='quantity',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
    ]
