# Generated by Django 2.0.13 on 2019-10-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191026_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('timeOfWork', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
