# Generated by Django 2.0.13 on 2019-11-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_work_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
