# Generated by Django 2.0.13 on 2019-11-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fill10',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='service',
            name='fill100',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='service',
            name='fill50',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
    ]
