# Generated by Django 2.0.13 on 2019-11-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191102_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='fill10',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='price',
            name='fill100',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='price',
            name='fill50',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
    ]
