# Generated by Django 2.0.13 on 2019-11-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191102_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fill10',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='fill100',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='fill50',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
    ]
